//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionLesson
    {
        public int Id { get; set; }
        public int IdQuestion { get; set; }
        public int IdLesson { get; set; }
    }
}
